### ISSUE TITLE
Moving Nameserver of MyPaint.Org from MythicBeasts to Linode

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/website#41]
@jonnor After some though, I'm ready to cut over the nameservers of MyPaint.Org. I've addressed the issue with #40 by changing the domain pointing to it to mypaint.app. I will probably do the same for the community server since the `.app` domains require https and it easier to just do a CNAME or HTTP forward to mypaint.app than it is the other way around.

After Stablizing the Nameservers and the DNS, then the next course of action would be to transfer the domain to an account own by the community. 

So if you can change over the nameservers over to linode that would be a great help. I should have everything setup on the DNS over there to at least keep the Community Server. Probably the only thing would break is the mail forwarding that from what I can glance.

Here are the url listed for Linode namserver:
ns1.linode.com

They can go up to ns5.linode.com

Thank you.

**Comment by jonnor** [comment]
Hi @odysseywestra - ack on the need to change to Linode nameservers. Just a few questions to clarify so that it goes smoothly:

Should I switch over to linode in one step, ie *replace* existing mythicbeast DNS entries with Linode?

Should I do it at earliest convenience, or do you have requirements for the timing? I am available CET evenings, today-Tueday.

**Comment by odysseywestra** [comment]
What I can do is give you access to the DNS records on linode so you can go over them and correct them if need before we cut over the name servers. 

You can just leave the mythic beast name servers at the bottom, but your domain registrar will treat the `ns1.linode.com` as the start of authority for the `mypaint.org` domain. As long as we get it done over the weekend, I'm available easily to correct any errors. Same with you during the week just PST instead. So my morning will be your evening if that makes sense.

**Comment by odysseywestra** [comment]
Sent you (@jonnor) an invite to the Linode account and gave you rw access to the `mypaint.app` and `mypaint.org` domains.
